{"name": "新增同步配置", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.", "trace": "fixturefunc = <function step_sync_config at 0x00000179E2333940>\nrequest = <FixtureRequest for <Function test_新增同步配置>>\nkwargs = {'page': <Page url='https://192.168.148.174:31000/sub-app-unity/userSync'>, 'sync_config': '| 名称     | 数据源  | 同步模式 | 任务时间 | 错误阈值 | 日志保留周期 |\\n| AD域同步 | 70.235 | 周期同步 | 周 星期一 00:00 | 10 | 30 |'}\n\n    def call_fixture_func(\n        fixturefunc: \"_FixtureFunc[FixtureValue]\", request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\n.venv\\lib\\site-packages\\_pytest\\fixtures.py:908: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_cases\\step_defs\\bms\\test_01_user_sync.py:62: in step_sync_config\n    UseSyncPage(page).set_sync_config(sync_config_param)\npages\\bms\\user_sync_page.py:125: in set_sync_config\n    self.page.locator(\"li\").get_by_text(sync_config_param.get(\"数据源\"), exact=True).click()\n.venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py:14764: in click\n    self._sync(\n.venv\\lib\\site-packages\\playwright\\_impl\\_locator.py:153: in click\n    return await self._frame.click(self._selector, strict=True, **params)\n.venv\\lib\\site-packages\\playwright\\_impl\\_frame.py:488: in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:509: in wrap_api_call\n    return await cb()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Channel object at 0x00000179E24F9F70>\nmethod = 'click'\nparams = {'selector': 'li >> internal:text=\"70.235\"s', 'strict': True}\nreturn_as_dict = False\n\n    async def inner_send(\n        self, method: str, params: Optional[Dict], return_as_dict: bool\n    ) -> Any:\n        if params is None:\n            params = {}\n        if self._connection._error:\n            error = self._connection._error\n            self._connection._error = None\n            raise error\n        callback = self._connection._send_message_to_server(\n            self._object, method, _filter_none(params)\n        )\n        done, _ = await asyncio.wait(\n            {\n                self._connection._transport.on_error_future,\n                callback.future,\n            },\n            return_when=asyncio.FIRST_COMPLETED,\n        )\n        if not callback.future.done():\n            callback.future.cancel()\n>       result = next(iter(done)).result()\nE       playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.\n\n.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:97: TimeoutError"}, "description": "E:\\Wondersoft_AutoTest\\test_cases\\features\\bms\\user_sync.feature: 新增同步配置", "steps": [{"name": "打开网站：'https://192.168.148.174:31000/'", "status": "passed", "parameters": [{"name": "url", "value": "'https://192.168.148.174:31000/'"}], "start": 1719193004619, "stop": 1719193004880}, {"name": "判断是否需要重新登录", "status": "passed", "parameters": [{"name": "full_url", "value": "'https://192.168.148.174:31000/portal-login'"}, {"name": "username", "value": "'admin'"}, {"name": "password", "value": "'Ws-123456'"}], "start": 1719193004881, "stop": 1719193006902}, {"name": "点击一级菜单：'用户管理'", "status": "passed", "parameters": [{"name": "men", "value": "'用户管理'"}], "start": 1719193006903, "stop": 1719193006967}, {"name": "点击二级菜单：'用户同步管理'下的三级菜单：'用户同步'", "status": "passed", "parameters": [{"name": "sec_men", "value": "'用户同步管理'"}, {"name": "thi_men", "value": "'用户同步'"}], "start": 1719193006968, "stop": 1719193007998}, {"name": "切换标签页：'同步配置'", "status": "passed", "parameters": [{"name": "tab", "value": "'同步配置'"}], "start": 1719193007999, "stop": 1719193009469}, {"name": "点击按钮：'新增'", "status": "passed", "parameters": [{"name": "button", "value": "'新增'"}, {"name": "page_name", "value": "None"}], "start": 1719193009470, "stop": 1719193009598}, {"name": "设置同步配置参数：{'名称': 'AD域同步', '数据源': '70.235', '同步模式': '周期同步', '任务时间': '周 星期一 00:00', '错误阈值': '10', '日志保留周期': '30'}", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.\n", "trace": "  File \"E:\\Wondersoft_AutoTest\\.venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"E:\\Wondersoft_AutoTest\\pages\\bms\\user_sync_page.py\", line 125, in set_sync_config\n    self.page.locator(\"li\").get_by_text(sync_config_param.get(\"数据源\"), exact=True).click()\n  File \"E:\\Wondersoft_AutoTest\\.venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 14764, in click\n    self._sync(\n  File \"E:\\Wondersoft_AutoTest\\.venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 113, in _sync\n    return task.result()\n  File \"E:\\Wondersoft_AutoTest\\.venv\\lib\\site-packages\\playwright\\_impl\\_locator.py\", line 153, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n  File \"E:\\Wondersoft_AutoTest\\.venv\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"E:\\Wondersoft_AutoTest\\.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n  File \"E:\\Wondersoft_AutoTest\\.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 509, in wrap_api_call\n    return await cb()\n  File \"E:\\Wondersoft_AutoTest\\.venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 97, in inner_send\n    result = next(iter(done)).result()\n"}, "parameters": [{"name": "sync_config_param", "value": "{'名称': 'AD域同步', '数据源': '70.235', '同步模式': '周期同步', '任务时间': '周 星期一 00:00', '错误阈值': '10', '日志保留周期': '30'}"}], "start": 1719193009600, "stop": 1719193040061}], "start": 1719193004618, "stop": 1719193040062, "uuid": "2d0e422d-50a4-4d0b-9b8b-8956aef9a7b5", "historyId": "0adaa47688bbd938833b356937fe60ae", "testCaseId": "f63c61be411065c6607ab8d16439104c", "fullName": "test_cases.step_defs.bms.test_01_user_sync#test_新增同步配置", "labels": [{"name": "feature", "value": "用户同步模块"}, {"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "test_cases.step_defs.bms"}, {"name": "suite", "value": "test_01_user_sync"}, {"name": "host", "value": "DESKTOP-ATHT3TO"}, {"name": "thread", "value": "11544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.step_defs.bms.test_01_user_sync"}]}