
元素定位超时：Timeout 30000ms exceeded.
详细报错信息如下：
Traceback (most recent call last):
  File "E:\Wondersoft_WebUITest\utils\ui_utils\base_page.py", line 353, in dropdown_locator_by_para
    self.dropdown_check_value(select_value)
  File "E:\Wondersoft_WebUITest\utils\ui_utils\base_page.py", line 399, in dropdown_check_value
    ExceptionHandle().handle_exception(e)
  File "E:\Wondersoft_WebUITest\utils\ui_utils\base_page.py", line 397, in dropdown_check_value
    dropdown_locator.locator('//span[text()="' + i + '"]').click()
  File "E:\Wondersoft_WebUITest\venv\lib\site-packages\playwright\sync_api\_generated.py", line 14764, in click
    self._sync(
  File "E:\Wondersoft_WebUITest\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 113, in _sync
    return task.result()
  File "E:\Wondersoft_WebUITest\venv\lib\site-packages\playwright\_impl\_locator.py", line 153, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "E:\Wondersoft_WebUITest\venv\lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "E:\Wondersoft_WebUITest\venv\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "E:\Wondersoft_WebUITest\venv\lib\site-packages\playwright\_impl\_connection.py", line 509, in wrap_api_call
    return await cb()
  File "E:\Wondersoft_WebUITest\venv\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.

